/sensor_01/sensor_stream:
  ros__parameters:
    ip: "10.18.18.202"
    channel: 1
    serial: "01"
    calibrate: false
    pub_gray_img: true
    pub_binary_img: true
    frame_rate: 20

/sensor_01/feature_extraction:
  ros__parameters:
    serial: "01"
    line_num: 7
    calibrate: false
    frame_rate: 20
